// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCNmHnBhBKlTxk9_C2y7Aicxoa0_a6JTfQ',
    appId: '1:439084392453:web:842938526df2702afdfc6c',
    messagingSenderId: '439084392453',
    projectId: 'itunes-video-app',
    authDomain: 'itunes-video-app.firebaseapp.com',
    storageBucket: 'itunes-video-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlae9FHcCO_aVrqrTEjGmz3_X9ZIQgXOI',
    appId: '1:439084392453:android:3162b774dd40dc2efdfc6c',
    messagingSenderId: '439084392453',
    projectId: 'itunes-video-app',
    storageBucket: 'itunes-video-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAAI7YY1UtZ0d4MDRa3Jc_q9tLNFViTRU',
    appId: '1:439084392453:ios:6325c87482ed5abefdfc6c',
    messagingSenderId: '439084392453',
    projectId: 'itunes-video-app',
    storageBucket: 'itunes-video-app.appspot.com',
    iosClientId: '439084392453-bna945a5omoqvbhf5qtqmrkl5imq9p6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.itunesVideoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAAI7YY1UtZ0d4MDRa3Jc_q9tLNFViTRU',
    appId: '1:439084392453:ios:6325c87482ed5abefdfc6c',
    messagingSenderId: '439084392453',
    projectId: 'itunes-video-app',
    storageBucket: 'itunes-video-app.appspot.com',
    iosClientId: '439084392453-bna945a5omoqvbhf5qtqmrkl5imq9p6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.itunesVideoApp',
  );
}
